# Site settings
title: Andrey Morskov Ruby developer
email: accessd0@gmail.com
description: "Website about me"
baseurl: ""
url: "http://morskov.com"

# Build settings
markdown: kramdown
# permalink: pretty
permalink: /:categories/:year/:month/:day/:title

exclude: [".rvmrc", "README.md", "Rakefile", "vendor"]
highlighter: rouge

author:
  name: Andrey Morskov
  email: accessd0@gmail.com
