- name: Hello Baby
  image: hellobaby.png
  url: https://babyalbum.com
  oneliner: An ultimate ecosystem of mobile apps for parents and future parents
  role: Backend developer
  description: >
    <p>
    Developed a backend for mobile applications, admin panels. Has written integrations with external services such as Amplitude, Adjust, AppsFlyer, Branch.
    </p>
    <p></p>
    My key achievements:
    <br/>
    I wrote a service that implements shared subscriptions for several apps
    <br/>
    Implemented A / B testing and sales analytics
    <br/>
    Made logging to Graylog
    <br/>
    Collecting metrics and alerts in Prometheus
    <br/>
    I made the infrastructure in Google Cloud using Ansible, used Docker and Kubernetes
    <p></p>
  technologies:
    - Ruby
    - Rails
    - Docker
    - Google Cloud
    - Kubernetes
    - Prometheus
    - Graylog
    - Ansible
    - MySQL

- name: Servers.com
  image: serverscom.png
  url: https://servers.com
  oneliner: Servers.com is a global IaaS hosting platform that provides an automated hybrid cloud ready infrastructure
  role: Backend developer
  description: >
    Migration from legacy code. Mostly I was working on baremetal servers zero-touch automatic provisioning.
    <p></p>
    My key achievements:
    <br/>
    Network automatic provisioning on Brocade VDX/ICX switches, particularly automatization of VXLAN provisioning
    <br/>
    Firewall as a service feature with <a href="http://www.brocade.com/en/products-services/software-networking/network-functions-virtualization/vrouter.html">Brocade vRouter</a>
    <br/>
    Microservice for interaction with DELL iDrac SOAP based protocol <a href="https://www.dmtf.org/standards/wsman" target="_blank">WS-Man</a>
    <br/>
    Tool for generation config for switches
    <br/>
    I've made deploy bot for Slack using <a href="https://github.com/slack-ruby/slack-ruby-bot" target="_blank">https://github.com/slack-ruby/slack-ruby-bot</a>
    <br/>
    Had provisioned 500 servers in one working day
    <p></p>
    Other things:
    <br/>
    Work on API for js app. Many integrations with third-party services.
    Refactoring, capistrano notifications to jabber, <a href="https://github.com/Undev/errbit" target="_blank">Errbit</a> integration.
    Migrating deployment infrastructure from capistrano to Ansible.

  technologies:
    - Ruby
    - Rack
    - Sinatra
    - EventMachine
    - Concurrency with Fibers
    - API with <a href="https://github.com/ruby-grape/grape" target="_blank">Grape</a>
    - MySQL
    - Rspec

- name: Gigtest.ru
  image: gigtest.jpg
  url: https://gigtest.ru
  oneliner: My own project. Gigtest.ru is a service of remote hygienic training and testing. Works only in Russia.
  role: Full-stack developer
  description: >
    Development from scratch. Developed key features such are: video conferences with WebRTC, education and test processes,
      analytics. Administrate server.
  technologies:
    - PHP
    - NodeJS
    - Yii Framework 2
    - MySQL
    - WebRTC

- name: Beacon Gate
  image: beacon.jpg
  url:
  oneliner: My own project with BLE and IBeacon technologies
  role: Full-stack developer
  description: >
    Apply device for opening doors by just a coming near to the door or gates. Bluetooth module and smartphone interact automaticly.
    It was really interesting to programming bluetooth module and develop for iOS.
  technologies:
    - <a href="https://www.silabs.com/products/wireless/bluetooth/bluetooth-smart-modules/Pages/ble112-bluetooth-smart-module.aspx" target="_blank">Bluegiga BLE112 Bluetooth Smart Module</a>
    - Objective C
    - Bluegiga BGScript
    - Soldering-iron

- name: UpToPromo
  image: uptopromo.png
  url: http://uptopromo.com/en
  oneliner: A full-featured links exchange service
  role: Full-stack developer
  description: >
    Development from scratch. Work on billing, fin statistics, content analysis universal analyst entities in the form of graphs(dashboard),
    system notifications, queue optimization, <a href="https://github.com/glebm/rails_email_preview/pull/14" target="_blank">preview emails with ability to send test messages</a>,
    <a href="https://github.com/accessd/rails-settings-ui" target="_blank">application settings interface</a>,
    editing content pages through <a href="http://jejacks0n.github.io/mercury/" target="_blank">Mercury editor</a>, redesign and etc.
  technologies:
    - Ruby on the edge
    - Rails on the edge
    - PostgreSQL
    - <a href="https://github.com/mperham/sidekiq" target="_blank">Sidekiq</a>
    - Rspec, Capybara
    - <a href="http://knockoutjs.com/" target="_blank">Knockout.js</a>
    - Bootstrap 3

- name: Photographer
  image: morskova.jpg
  url: http://morskova.com
  oneliner: Website with portfolio for my wife
  role: Full-stack developer
  description: >
    Simple website working on new cool technologies!
  technologies:
    - <a href="http://elixir-lang.org/" target="_blank">Elixir</a>
    - <a href="http://www.phoenixframework.org/" target="_blank">Phoenix</a>
    - PostgreSQL

- name: DrinkAdvisor
  image: drinkadvisor.png
  url: http://drinkadvisor.com
  oneliner: Bars & Drinks guide
  role: Full-stack / Lead developer
  description: >
    Social network for nightlife lovers. The website was designed and api for mobile applications,
    functional website and applications was approximately the same in the end have only mobile application.
    Integration with social networks Twitter and Facebook, push messages for the iPhone and Android,
    queue implementation through <a href="http://gearman.org/" target="_blank">Gearman</a>,
    geo-positioning via HTML5 Geolocation Api and <a href="http://postgis.net/" target="_blank">Postgis</a>
  technologies:
    - PHP
    - Yii framework
    - <a href="http://gearman.org/" target="_blank">Gearman</a>
    - PostgreSQL
    - <a href="http://postgis.net/" target="_blank">Postgis</a>
    - Jquery

- name: TourSovet
  image: toursovet.png
  url: http://toursovet.ru
  oneliner: Travel company site
  role: Full-stack developer
  description: >
    Site travel company. Import tours, online sales. Redesign. Api for mobile application.
    Online chat on Metal; rake tasks for logic,
    parsing external sources.
  technologies:
    - Rails 2.3
    - MySQL
    - <a href="https://github.com/collectiveidea/delayed_job" target="_blank">delayed_job</a>
    - JQuery
    - SOAP

- name: Tarification
  image: tarification.png
  url: #
  oneliner: Intended for economists working in health facilities budget
  role: Full-stack developer
  description: >
    Payroll accounting and various reports in excel. Connect to remote MSSQL databases.
  technologies:
    - Rails 3
    - Ruby 1.9
    - MSSQL
    - Memcached
    - <a href="http://www.sencha.com/products/extjs/" target="_blank">ExtJS 3</a>

- name: Estimates
  image: estimates.png
  url: #
  oneliner: ERP system for compiling estimates for sanitary-epidemiological services
  role: Full-stack developer
  description: >
    Established interaction between managers, accountants, lawyers.
    Price list with <a href="http://www.jstree.com/" target="_blank">jsTree</a>.
    More reports in PDF and DOCX formats.
  technologies:
    - Rails 3
    - Ruby 1.9
    - MySQL
    - <a href="https://github.com/prawnpdf/prawn" target="_blank">Prawn gem</a>
    - JQuery
    - Bootstrap

- name: My salon
  image: closed.jpg
  url: https://vk.com/app1922478
  oneliner: Backend for online flash game in social network <a href="http://vk.com/" target="_blank">VKontakte</a>
  role: Backend developer
  description: >
    The application has completed its way, nevertheless it was a useful experience. Api with xml responses and much app logic. Lightweight Zend Framework:)
  technologies:
    - PHP
    - <a href="http://framework.zend.com/" target="_blank">Zend Framework</a>
    - Mysql stored procedures
    - Memcached

- name: Redmine plugins
  image: redmine.png
  url: http://www.redmine.org/
  oneliner: Various inter-corporate plugins for <a href="http://www.redmine.org/" target="_blank">Redmine</a>
  role: Backend developer
  description: >
    Writing plugins. Workload optimization redmine (load testing application servers mongrel, passenger, thin, unicorn. Eventually settled on unicorn + ree 1.8.7)
  technologies:
    - Rails 2.3
    - Ruby 1.8
